.TH "obj/Debug/net6.0-windows/AddVideoPopup.g.i.cs" 3 "Sun May 7 2023" "BetterYouTubeFeed" \" -*- nroff -*-
.ad l
.nh
.SH NAME
obj/Debug/net6.0-windows/AddVideoPopup.g.i.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBbyt\&.AddVideoPopup\fP"
.br
.RI "AddVideoPopup\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBbyt\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for BetterYouTubeFeed from the source code\&.
