.TH "BetterYouTubeFeed.MVVM.ViewModel" 3 "Sun May 7 2023" "BetterYouTubeFeed" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BetterYouTubeFeed.MVVM.ViewModel
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBChannelListViewModel\fP"
.br
.ti -1c
.RI "class \fBHomeViewModel\fP"
.br
.ti -1c
.RI "class \fBMainViewModel\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for BetterYouTubeFeed from the source code\&.
