.TH "BetterYouTubeFeed.MVVM.View.HomeView" 3 "Sun May 7 2023" "BetterYouTubeFeed" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BetterYouTubeFeed.MVVM.View.HomeView \- Interaction logic for HomeView\&.xaml\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits System\&.Windows\&.Controls\&.UserControl, and System\&.Windows\&.Markup\&.IComponentConnector\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHomeView\fP ()"
.br
.ti -1c
.RI "void \fBInitializeComponent\fP ()"
.br
.RI "InitializeComponent\&. "
.ti -1c
.RI "void \fBInitializeComponent\fP ()"
.br
.RI "InitializeComponent\&. "
.in -1c
.SH "Detailed Description"
.PP 
Interaction logic for HomeView\&.xaml\&. 

HomeView\&. 
.PP
Definition at line \fB21\fP of file \fBHomeView\&.xaml\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "BetterYouTubeFeed\&.MVVM\&.View\&.HomeView\&.HomeView ()"

.PP
Definition at line \fB23\fP of file \fBHomeView\&.xaml\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void BetterYouTubeFeed\&.MVVM\&.View\&.HomeView\&.InitializeComponent ()"

.PP
InitializeComponent\&. 
.PP
Definition at line \fB51\fP of file \fBHomeView\&.g\&.cs\fP\&.
.SS "void BetterYouTubeFeed\&.MVVM\&.View\&.HomeView\&.InitializeComponent ()"

.PP
InitializeComponent\&. 
.PP
Definition at line \fB51\fP of file \fBHomeView\&.g\&.i\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BetterYouTubeFeed from the source code\&.
