.TH "BetterYouTubeFeed.Migrations.Init" 3 "Sun May 7 2023" "BetterYouTubeFeed" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BetterYouTubeFeed.Migrations.Init \-  

.SH SYNOPSIS
.br
.PP
.PP
Inherits Migration\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBUp\fP (MigrationBuilder migrationBuilder)"
.br
.ti -1c
.RI "override void \fBDown\fP (MigrationBuilder migrationBuilder)"
.br
.ti -1c
.RI "override void \fBBuildTargetModel\fP (ModelBuilder modelBuilder)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
Definition at line \fB8\fP of file \fB20230507195553_Init\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override void BetterYouTubeFeed\&.Migrations\&.Init\&.BuildTargetModel (ModelBuilder modelBuilder)\fC [protected]\fP"

.PP

.PP
Definition at line \fB18\fP of file \fB20230507195553_Init\&.Designer\&.cs\fP\&.
.SS "override void BetterYouTubeFeed\&.Migrations\&.Init\&.Down (MigrationBuilder migrationBuilder)\fC [protected]\fP"

.PP

.PP
Definition at line \fB87\fP of file \fB20230507195553_Init\&.cs\fP\&.
.SS "override void BetterYouTubeFeed\&.Migrations\&.Init\&.Up (MigrationBuilder migrationBuilder)\fC [protected]\fP"

.PP

.PP
Definition at line \fB11\fP of file \fB20230507195553_Init\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BetterYouTubeFeed from the source code\&.
