.TH "BetterYouTubeFeed.MVVM.ViewModel.ChannelListViewModel" 3 "Sun May 7 2023" "BetterYouTubeFeed" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BetterYouTubeFeed.MVVM.ViewModel.ChannelListViewModel
.SH SYNOPSIS
.br
.PP
.PP
Inherits BetterYouTubeFeed\&.Core\&.ObservableObject\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBChannelListViewModel\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB6\fP of file \fBChannelListViewModel\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "BetterYouTubeFeed\&.MVVM\&.ViewModel\&.ChannelListViewModel\&.ChannelListViewModel ()"

.PP
Definition at line \fB8\fP of file \fBChannelListViewModel\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BetterYouTubeFeed from the source code\&.
