.TH "obj/Debug/net6.0-windows/BetterYouTubeFeed_1adeeh3h_wpftmp.AssemblyInfo.cs" 3 "Sun May 7 2023" "BetterYouTubeFeed" \" -*- nroff -*-
.ad l
.nh
.SH NAME
obj/Debug/net6.0-windows/BetterYouTubeFeed_1adeeh3h_wpftmp.AssemblyInfo.cs
.SH SYNOPSIS
.br
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for BetterYouTubeFeed from the source code\&.
