.TH "BetterYouTubeFeed.Core.RelayCommand" 3 "Sun May 7 2023" "BetterYouTubeFeed" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BetterYouTubeFeed.Core.RelayCommand
.SH SYNOPSIS
.br
.PP
.PP
Inherits ICommand\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRelayCommand\fP (Action< object > execute, Func< object, bool > canExecute=null)"
.br
.ti -1c
.RI "bool \fBCanExecute\fP (object parameter)"
.br
.ti -1c
.RI "void \fBExecute\fP (object parameter)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "EventHandler \fBCanExecuteChanged\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB6\fP of file \fBRelayCommand\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "BetterYouTubeFeed\&.Core\&.RelayCommand\&.RelayCommand (Action< object > execute, Func< object, bool > canExecute = \fCnull\fP)"

.PP
Definition at line \fB17\fP of file \fBRelayCommand\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "bool BetterYouTubeFeed\&.Core\&.RelayCommand\&.CanExecute (object parameter)"

.PP
Definition at line \fB23\fP of file \fBRelayCommand\&.cs\fP\&.
.SS "void BetterYouTubeFeed\&.Core\&.RelayCommand\&.Execute (object parameter)"

.PP
Definition at line \fB28\fP of file \fBRelayCommand\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "EventHandler BetterYouTubeFeed\&.Core\&.RelayCommand\&.CanExecuteChanged\fC [add]\fP, \fC [remove]\fP"

.PP
Definition at line \fB11\fP of file \fBRelayCommand\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BetterYouTubeFeed from the source code\&.
