.TH "BetterYouTubeFeed.MVVM.ViewModel.MainViewModel" 3 "Sun May 7 2023" "BetterYouTubeFeed" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BetterYouTubeFeed.MVVM.ViewModel.MainViewModel
.SH SYNOPSIS
.br
.PP
.PP
Inherits BetterYouTubeFeed\&.Core\&.ObservableObject\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMainViewModel\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBHomeViewModel\fP \fBHomeVM\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "object \fBCurrentView\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB10\fP of file \fBMainViewModel\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "BetterYouTubeFeed\&.MVVM\&.ViewModel\&.MainViewModel\&.MainViewModel ()"

.PP
Definition at line \fB27\fP of file \fBMainViewModel\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "object BetterYouTubeFeed\&.MVVM\&.ViewModel\&.MainViewModel\&.CurrentView\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line \fB16\fP of file \fBMainViewModel\&.cs\fP\&.
.SS "\fBHomeViewModel\fP BetterYouTubeFeed\&.MVVM\&.ViewModel\&.MainViewModel\&.HomeVM\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line \fB12\fP of file \fBMainViewModel\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BetterYouTubeFeed from the source code\&.
