.TH "BetterYouTubeFeed.Models" 3 "Sun May 7 2023" "BetterYouTubeFeed" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BetterYouTubeFeed.Models
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAccount\fP"
.br
.RI "Entity Framework table definition defines Account table class\&. "
.ti -1c
.RI "class \fBChannel\fP"
.br
.RI "Entity Framework table definition defines Channel table class\&. "
.ti -1c
.RI "class \fBVideo\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for BetterYouTubeFeed from the source code\&.
