.TH "BetterYouTubeFeed.App" 3 "Sun May 7 2023" "BetterYouTubeFeed" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BetterYouTubeFeed.App \- Interaction logic for App\&.xaml\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits Application\&.
.SH "Detailed Description"
.PP 
Interaction logic for App\&.xaml\&. 
.PP
Definition at line \fB16\fP of file \fBApp\&.xaml\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BetterYouTubeFeed from the source code\&.
