.TH "BetterYouTubeFeed.Models.Video" 3 "Sun May 7 2023" "BetterYouTubeFeed" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BetterYouTubeFeed.Models.Video
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBVideo\fP ()"
.br
.ti -1c
.RI "\fBVideo\fP (string videoId, string title, string uploadDate, string downloadDate, string thumbnailLink, string? channelId)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBVideoId\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBTitle\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBUploadDate\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBDownloadDate\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBThumbnailLink\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string? \fBChannelId\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "bool \fBwatched\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB6\fP of file \fBVideo\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "BetterYouTubeFeed\&.Models\&.Video\&.Video ()"

.PP
Definition at line \fB20\fP of file \fBVideo\&.cs\fP\&.
.SS "BetterYouTubeFeed\&.Models\&.Video\&.Video (string videoId, string title, string uploadDate, string downloadDate, string thumbnailLink, string? channelId)"

.PP
Definition at line \fB21\fP of file \fBVideo\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "string? BetterYouTubeFeed\&.Models\&.Video\&.ChannelId\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line \fB18\fP of file \fBVideo\&.cs\fP\&.
.SS "string BetterYouTubeFeed\&.Models\&.Video\&.DownloadDate\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line \fB15\fP of file \fBVideo\&.cs\fP\&.
.SS "string BetterYouTubeFeed\&.Models\&.Video\&.ThumbnailLink\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line \fB17\fP of file \fBVideo\&.cs\fP\&.
.SS "string BetterYouTubeFeed\&.Models\&.Video\&.Title\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line \fB11\fP of file \fBVideo\&.cs\fP\&.
.SS "string BetterYouTubeFeed\&.Models\&.Video\&.UploadDate\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line \fB13\fP of file \fBVideo\&.cs\fP\&.
.SS "string BetterYouTubeFeed\&.Models\&.Video\&.VideoId\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line \fB9\fP of file \fBVideo\&.cs\fP\&.
.SS "bool BetterYouTubeFeed\&.Models\&.Video\&.watched\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line \fB19\fP of file \fBVideo\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BetterYouTubeFeed from the source code\&.
