.TH "BetterYouTubeFeed.Migrations.BYTFContextModelSnapshot" 3 "Sun May 7 2023" "BetterYouTubeFeed" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BetterYouTubeFeed.Migrations.BYTFContextModelSnapshot
.SH SYNOPSIS
.br
.PP
.PP
Inherits ModelSnapshot\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBBuildModel\fP (ModelBuilder modelBuilder)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB13\fP of file \fBBYTFContextModelSnapshot\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override void BetterYouTubeFeed\&.Migrations\&.BYTFContextModelSnapshot\&.BuildModel (ModelBuilder modelBuilder)\fC [protected]\fP"

.PP
Definition at line \fB15\fP of file \fBBYTFContextModelSnapshot\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BetterYouTubeFeed from the source code\&.
