.TH "BetterYouTubeFeed.Models.Account" 3 "Sun May 7 2023" "BetterYouTubeFeed" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BetterYouTubeFeed.Models.Account \- Entity Framework table definition defines Account table class\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAccount\fP ()"
.br
.ti -1c
.RI "\fBAccount\fP (string accountId, string type, string authId, string name, string familyName, string givenName, string email, string customUrl, string imageUrl)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBAccountId\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBType\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBAuthId\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBName\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBFamilyName\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBGivenName\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBEmail\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBImageUrl\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string? \fBCustomUrl\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "ICollection< \fBChannel\fP >? \fBChannels\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Entity Framework table definition defines Account table class\&. 
.PP
Definition at line \fB12\fP of file \fBAccount\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "BetterYouTubeFeed\&.Models\&.Account\&.Account ()"

.PP
Definition at line \fB34\fP of file \fBAccount\&.cs\fP\&.
.SS "BetterYouTubeFeed\&.Models\&.Account\&.Account (string accountId, string type, string authId, string name, string familyName, string givenName, string email, string customUrl, string imageUrl)"

.PP
Definition at line \fB35\fP of file \fBAccount\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "string BetterYouTubeFeed\&.Models\&.Account\&.AccountId\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line \fB15\fP of file \fBAccount\&.cs\fP\&.
.SS "string BetterYouTubeFeed\&.Models\&.Account\&.AuthId\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line \fB19\fP of file \fBAccount\&.cs\fP\&.
.SS "ICollection<\fBChannel\fP>? BetterYouTubeFeed\&.Models\&.Account\&.Channels\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line \fB32\fP of file \fBAccount\&.cs\fP\&.
.SS "string? BetterYouTubeFeed\&.Models\&.Account\&.CustomUrl\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line \fB30\fP of file \fBAccount\&.cs\fP\&.
.SS "string BetterYouTubeFeed\&.Models\&.Account\&.Email\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line \fB27\fP of file \fBAccount\&.cs\fP\&.
.SS "string BetterYouTubeFeed\&.Models\&.Account\&.FamilyName\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line \fB23\fP of file \fBAccount\&.cs\fP\&.
.SS "string BetterYouTubeFeed\&.Models\&.Account\&.GivenName\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line \fB25\fP of file \fBAccount\&.cs\fP\&.
.SS "string BetterYouTubeFeed\&.Models\&.Account\&.ImageUrl\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line \fB29\fP of file \fBAccount\&.cs\fP\&.
.SS "string BetterYouTubeFeed\&.Models\&.Account\&.Name\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line \fB21\fP of file \fBAccount\&.cs\fP\&.
.SS "string BetterYouTubeFeed\&.Models\&.Account\&.Type\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line \fB17\fP of file \fBAccount\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BetterYouTubeFeed from the source code\&.
