.TH "BetterYouTubeFeed" 3 "Sun May 7 2023" "BetterYouTubeFeed" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BetterYouTubeFeed
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBCore\fP"
.br
.ti -1c
.RI "namespace \fBData\fP"
.br
.ti -1c
.RI "namespace \fBMigrations\fP"
.br
.ti -1c
.RI "namespace \fBModels\fP"
.br
.ti -1c
.RI "namespace \fBMVVM\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBApp\fP"
.br
.RI "Interaction logic for App\&.xaml\&. "
.ti -1c
.RI "class \fBYouTubeDataAPI\fP"
.br
.RI "Class that abstracts communication with YouTube Data API\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for BetterYouTubeFeed from the source code\&.
