.TH "BetterYouTubeFeed.Models.Channel" 3 "Sun May 7 2023" "BetterYouTubeFeed" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BetterYouTubeFeed.Models.Channel \- Entity Framework table definition defines Channel table class\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBChannel\fP ()"
.br
.ti -1c
.RI "\fBChannel\fP (string channelId, string name, string customUrl, string imageUrl, string description, string ytaccountId)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBChannelId\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBName\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBCustomUrl\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBImageUrl\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string? \fBDescription\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string? \fBAccountId\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "ICollection< \fBVideo\fP >? \fBVideos\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Entity Framework table definition defines Channel table class\&. 
.PP
Definition at line \fB11\fP of file \fBChannel\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "BetterYouTubeFeed\&.Models\&.Channel\&.Channel ()"

.PP
Definition at line \fB24\fP of file \fBChannel\&.cs\fP\&.
.SS "BetterYouTubeFeed\&.Models\&.Channel\&.Channel (string channelId, string name, string customUrl, string imageUrl, string description, string ytaccountId)"

.PP
Definition at line \fB26\fP of file \fBChannel\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "string? BetterYouTubeFeed\&.Models\&.Channel\&.AccountId\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line \fB22\fP of file \fBChannel\&.cs\fP\&.
.SS "string BetterYouTubeFeed\&.Models\&.Channel\&.ChannelId\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line \fB14\fP of file \fBChannel\&.cs\fP\&.
.SS "string BetterYouTubeFeed\&.Models\&.Channel\&.CustomUrl\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line \fB18\fP of file \fBChannel\&.cs\fP\&.
.SS "string? BetterYouTubeFeed\&.Models\&.Channel\&.Description\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line \fB21\fP of file \fBChannel\&.cs\fP\&.
.SS "string BetterYouTubeFeed\&.Models\&.Channel\&.ImageUrl\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line \fB20\fP of file \fBChannel\&.cs\fP\&.
.SS "string BetterYouTubeFeed\&.Models\&.Channel\&.Name\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line \fB16\fP of file \fBChannel\&.cs\fP\&.
.SS "ICollection<\fBVideo\fP>? BetterYouTubeFeed\&.Models\&.Channel\&.Videos\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line \fB23\fP of file \fBChannel\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BetterYouTubeFeed from the source code\&.
