.TH "byt" 3 "Sun May 7 2023" "BetterYouTubeFeed" \" -*- nroff -*-
.ad l
.nh
.SH NAME
byt
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAddVideoPopup\fP"
.br
.RI "AddVideoPopup\&. "
.ti -1c
.RI "class \fBApp\fP"
.br
.RI "App\&. "
.ti -1c
.RI "class \fBMainWindow\fP"
.br
.RI "Interaction logic for MainWindow\&.xaml\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for BetterYouTubeFeed from the source code\&.
