.TH "Migrations/BYTFContextModelSnapshot.cs" 3 "Sun May 7 2023" "BetterYouTubeFeed" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Migrations/BYTFContextModelSnapshot.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBetterYouTubeFeed\&.Migrations\&.BYTFContextModelSnapshot\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBBetterYouTubeFeed\fP"
.br
.ti -1c
.RI "namespace \fBBetterYouTubeFeed\&.Migrations\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for BetterYouTubeFeed from the source code\&.
