.TH "obj/Debug/net6.0-windows Directory Reference" 3 "Sun May 7 2023" "BetterYouTubeFeed" \" -*- nroff -*-
.ad l
.nh
.SH NAME
obj/Debug/net6.0-windows Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBMVVM\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fB\&.NETCoreApp,Version=v6\&.0\&.AssemblyAttributes\&.cs\fP"
.br
.ti -1c
.RI "file \fBAddVideoPopup\&.g\&.i\&.cs\fP"
.br
.ti -1c
.RI "file \fBApp\&.g\&.cs\fP"
.br
.ti -1c
.RI "file \fBApp\&.g\&.i\&.cs\fP"
.br
.ti -1c
.RI "file \fBBetterYouTubeFeed\&.AssemblyInfo\&.cs\fP"
.br
.ti -1c
.RI "file \fBBetterYouTubeFeed_1adeeh3h_wpftmp\&.AssemblyInfo\&.cs\fP"
.br
.ti -1c
.RI "file \fBBetterYouTubeFeed_1veurjzm_wpftmp\&.AssemblyInfo\&.cs\fP"
.br
.ti -1c
.RI "file \fBBetterYouTubeFeed_k2ixrlvx_wpftmp\&.AssemblyInfo\&.cs\fP"
.br
.ti -1c
.RI "file \fBBetterYouTubeFeed_lx5d1ibp_wpftmp\&.AssemblyInfo\&.cs\fP"
.br
.ti -1c
.RI "file \fBBetterYouTubeFeed_scu2c0q4_wpftmp\&.AssemblyInfo\&.cs\fP"
.br
.ti -1c
.RI "file \fBBetterYouTubeFeed_ttnz0gxq_wpftmp\&.AssemblyInfo\&.cs\fP"
.br
.ti -1c
.RI "file \fBBetterYouTubeFeed_tw1j03lz_wpftmp\&.AssemblyInfo\&.cs\fP"
.br
.ti -1c
.RI "file \fBGeneratedInternalTypeHelper\&.g\&.cs\fP"
.br
.ti -1c
.RI "file \fBGeneratedInternalTypeHelper\&.g\&.i\&.cs\fP"
.br
.ti -1c
.RI "file \fBMainWindow\&.g\&.cs\fP"
.br
.ti -1c
.RI "file \fBMainWindow\&.g\&.i\&.cs\fP"
.br
.in -1c
