.TH "obj/Debug/net6.0-windows/MVVM/View Directory Reference" 3 "Sun May 7 2023" "BetterYouTubeFeed" \" -*- nroff -*-
.ad l
.nh
.SH NAME
obj/Debug/net6.0-windows/MVVM/View Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBChannelListView\&.g\&.cs\fP"
.br
.ti -1c
.RI "file \fBChannelListView\&.g\&.i\&.cs\fP"
.br
.ti -1c
.RI "file \fBHomeView\&.g\&.cs\fP"
.br
.ti -1c
.RI "file \fBHomeView\&.g\&.i\&.cs\fP"
.br
.in -1c
