.TH "XamlGeneratedNamespace.GeneratedInternalTypeHelper" 3 "Sun May 7 2023" "BetterYouTubeFeed" \" -*- nroff -*-
.ad l
.nh
.SH NAME
XamlGeneratedNamespace.GeneratedInternalTypeHelper \- GeneratedInternalTypeHelper\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits System\&.Windows\&.Markup\&.InternalTypeHelper\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override object \fBCreateInstance\fP (System\&.Type type, System\&.Globalization\&.CultureInfo culture)"
.br
.RI "CreateInstance\&. "
.ti -1c
.RI "override object \fBGetPropertyValue\fP (System\&.Reflection\&.PropertyInfo propertyInfo, object target, System\&.Globalization\&.CultureInfo culture)"
.br
.RI "GetPropertyValue\&. "
.ti -1c
.RI "override void \fBSetPropertyValue\fP (System\&.Reflection\&.PropertyInfo propertyInfo, object target, object value, System\&.Globalization\&.CultureInfo culture)"
.br
.RI "SetPropertyValue\&. "
.ti -1c
.RI "override System\&.Delegate \fBCreateDelegate\fP (System\&.Type delegateType, object target, string handler)"
.br
.RI "CreateDelegate\&. "
.ti -1c
.RI "override void \fBAddEventHandler\fP (System\&.Reflection\&.EventInfo eventInfo, object target, System\&.Delegate handler)"
.br
.RI "AddEventHandler\&. "
.ti -1c
.RI "override object \fBCreateInstance\fP (System\&.Type type, System\&.Globalization\&.CultureInfo culture)"
.br
.RI "CreateInstance\&. "
.ti -1c
.RI "override object \fBGetPropertyValue\fP (System\&.Reflection\&.PropertyInfo propertyInfo, object target, System\&.Globalization\&.CultureInfo culture)"
.br
.RI "GetPropertyValue\&. "
.ti -1c
.RI "override void \fBSetPropertyValue\fP (System\&.Reflection\&.PropertyInfo propertyInfo, object target, object value, System\&.Globalization\&.CultureInfo culture)"
.br
.RI "SetPropertyValue\&. "
.ti -1c
.RI "override System\&.Delegate \fBCreateDelegate\fP (System\&.Type delegateType, object target, string handler)"
.br
.RI "CreateDelegate\&. "
.ti -1c
.RI "override void \fBAddEventHandler\fP (System\&.Reflection\&.EventInfo eventInfo, object target, System\&.Delegate handler)"
.br
.RI "AddEventHandler\&. "
.in -1c
.SH "Detailed Description"
.PP 
GeneratedInternalTypeHelper\&. 
.PP
Definition at line \fB20\fP of file \fBGeneratedInternalTypeHelper\&.g\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override void XamlGeneratedNamespace\&.GeneratedInternalTypeHelper\&.AddEventHandler (System::Reflection::EventInfo eventInfo, object target, System::Delegate handler)\fC [protected]\fP"

.PP
AddEventHandler\&. 
.PP
Definition at line \fB57\fP of file \fBGeneratedInternalTypeHelper\&.g\&.cs\fP\&.
.SS "override void XamlGeneratedNamespace\&.GeneratedInternalTypeHelper\&.AddEventHandler (System::Reflection::EventInfo eventInfo, object target, System::Delegate handler)\fC [protected]\fP"

.PP
AddEventHandler\&. 
.PP
Definition at line \fB57\fP of file \fBGeneratedInternalTypeHelper\&.g\&.i\&.cs\fP\&.
.SS "override System\&.Delegate XamlGeneratedNamespace\&.GeneratedInternalTypeHelper\&.CreateDelegate (System::Type delegateType, object target, string handler)\fC [protected]\fP"

.PP
CreateDelegate\&. 
.PP
Definition at line \fB47\fP of file \fBGeneratedInternalTypeHelper\&.g\&.cs\fP\&.
.SS "override System\&.Delegate XamlGeneratedNamespace\&.GeneratedInternalTypeHelper\&.CreateDelegate (System::Type delegateType, object target, string handler)\fC [protected]\fP"

.PP
CreateDelegate\&. 
.PP
Definition at line \fB47\fP of file \fBGeneratedInternalTypeHelper\&.g\&.i\&.cs\fP\&.
.SS "override object XamlGeneratedNamespace\&.GeneratedInternalTypeHelper\&.CreateInstance (System::Type type, System::Globalization::CultureInfo culture)\fC [protected]\fP"

.PP
CreateInstance\&. 
.PP
Definition at line \fB25\fP of file \fBGeneratedInternalTypeHelper\&.g\&.cs\fP\&.
.SS "override object XamlGeneratedNamespace\&.GeneratedInternalTypeHelper\&.CreateInstance (System::Type type, System::Globalization::CultureInfo culture)\fC [protected]\fP"

.PP
CreateInstance\&. 
.PP
Definition at line \fB25\fP of file \fBGeneratedInternalTypeHelper\&.g\&.i\&.cs\fP\&.
.SS "override object XamlGeneratedNamespace\&.GeneratedInternalTypeHelper\&.GetPropertyValue (System::Reflection::PropertyInfo propertyInfo, object target, System::Globalization::CultureInfo culture)\fC [protected]\fP"

.PP
GetPropertyValue\&. 
.PP
Definition at line \fB33\fP of file \fBGeneratedInternalTypeHelper\&.g\&.cs\fP\&.
.SS "override object XamlGeneratedNamespace\&.GeneratedInternalTypeHelper\&.GetPropertyValue (System::Reflection::PropertyInfo propertyInfo, object target, System::Globalization::CultureInfo culture)\fC [protected]\fP"

.PP
GetPropertyValue\&. 
.PP
Definition at line \fB33\fP of file \fBGeneratedInternalTypeHelper\&.g\&.i\&.cs\fP\&.
.SS "override void XamlGeneratedNamespace\&.GeneratedInternalTypeHelper\&.SetPropertyValue (System::Reflection::PropertyInfo propertyInfo, object target, object value, System::Globalization::CultureInfo culture)\fC [protected]\fP"

.PP
SetPropertyValue\&. 
.PP
Definition at line \fB40\fP of file \fBGeneratedInternalTypeHelper\&.g\&.cs\fP\&.
.SS "override void XamlGeneratedNamespace\&.GeneratedInternalTypeHelper\&.SetPropertyValue (System::Reflection::PropertyInfo propertyInfo, object target, object value, System::Globalization::CultureInfo culture)\fC [protected]\fP"

.PP
SetPropertyValue\&. 
.PP
Definition at line \fB40\fP of file \fBGeneratedInternalTypeHelper\&.g\&.i\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BetterYouTubeFeed from the source code\&.
